data = [
    {
        "job_title": "백엔드",
        "entry_tech_stacks": [
            {"tech_name": "Python", "percentage": 30},
            {"tech_name": "SQL", "percentage": 25},
            {"tech_name": "Django", "percentage": 20},
            {"tech_name": "Flask", "percentage": 10},
            {"tech_name": "PostgreSQL", "percentage": 8},
            {"tech_name": "Docker", "percentage": 5},
            {"tech_name": "Redis", "percentage": 2},
            {"tech_name": "MongoDB", "percentage": 1},
            {"tech_name": "GraphQL", "percentage": 1},
            {"tech_name": "Kubernetes", "percentage": 1},
            {"tech_name": "Celery", "percentage": 1},
            {"tech_name": "Nginx", "percentage": 1},
            {"tech_name": "Gunicorn", "percentage": 1},
            {"tech_name": "Jenkins", "percentage": 1},
            {"tech_name": "Ansible", "percentage": 1},
            {"tech_name": "Terraform", "percentage": 1},
            {"tech_name": "Linux", "percentage": 1},
            {"tech_name": "AWS", "percentage": 1},
            {"tech_name": "GCP", "percentage": 1},
            {"tech_name": "Azure", "percentage": 1},
            {"tech_name": "MySQL", "percentage": 1},
            {"tech_name": "SQLite", "percentage": 1},
            {"tech_name": "OracleDB", "percentage": 1},
            {"tech_name": "Selenium", "percentage": 1},
            {"tech_name": "Pandas", "percentage": 1},
            {"tech_name": "NumPy", "percentage": 1},
            {"tech_name": "Matplotlib", "percentage": 1},
            {"tech_name": "Pytest", "percentage": 1},
            {"tech_name": "Git", "percentage": 1}
        ],
        "experienced_tech_stacks": [
            {"tech_name": "Python", "percentage": 40},
            {"tech_name": "SQL", "percentage": 30},
            {"tech_name": "Django", "percentage": 25},
            {"tech_name": "Flask", "percentage": 15},
            {"tech_name": "PostgreSQL", "percentage": 10},
            {"tech_name": "Docker", "percentage": 8},
            {"tech_name": "Redis", "percentage": 5},
            {"tech_name": "MongoDB", "percentage": 4},
            {"tech_name": "GraphQL", "percentage": 4},
            {"tech_name": "Kubernetes", "percentage": 4},
            {"tech_name": "Celery", "percentage": 4},
            {"tech_name": "Nginx", "percentage": 3},
            {"tech_name": "Gunicorn", "percentage": 3},
            {"tech_name": "Jenkins", "percentage": 3},
            {"tech_name": "Ansible", "percentage": 2},
            {"tech_name": "Terraform", "percentage": 2},
            {"tech_name": "Linux", "percentage": 2},
            {"tech_name": "AWS", "percentage": 2},
            {"tech_name": "GCP", "percentage": 2},
            {"tech_name": "Azure", "percentage": 2},
            {"tech_name": "MySQL", "percentage": 2},
            {"tech_name": "SQLite", "percentage": 2},
            {"tech_name": "OracleDB", "percentage": 2},
            {"tech_name": "Selenium", "percentage": 1},
            {"tech_name": "Pandas", "percentage": 1},
            {"tech_name": "NumPy", "percentage": 1},
            {"tech_name": "Matplotlib", "percentage": 1},
            {"tech_name": "Pytest", "percentage": 1},
            {"tech_name": "Git", "percentage": 1}
        ]
    },
    {
        "job_title": "프론트엔드",
        "entry_tech_stacks": [
            {"tech_name": "JavaScript", "percentage": 35},
            {"tech_name": "React", "percentage": 25},
            {"tech_name": "CSS", "percentage": 20},
            {"tech_name": "HTML", "percentage": 10},
            {"tech_name": "Redux", "percentage": 5},
            {"tech_name": "TypeScript", "percentage": 4},
            {"tech_name": "SASS", "percentage": 3},
            {"tech_name": "Webpack", "percentage": 2},
            {"tech_name": "GraphQL", "percentage": 2},
            {"tech_name": "Apollo", "percentage": 2},
            {"tech_name": "Node.js", "percentage": 1},
            {"tech_name": "Express.js", "percentage": 1},
            {"tech_name": "Jest", "percentage": 1},
            {"tech_name": "Cypress", "percentage": 1},
            {"tech_name": "Webpack", "percentage": 1},
            {"tech_name": "Babel", "percentage": 1},
            {"tech_name": "D3.js", "percentage": 1},
            {"tech_name": "Three.js", "percentage": 1},
            {"tech_name": "Vue.js", "percentage": 1},
            {"tech_name": "Nuxt.js", "percentage": 1},
            {"tech_name": "Gatsby", "percentage": 1},
            {"tech_name": "Next.js", "percentage": 1},
            {"tech_name": "Svelte", "percentage": 1},
            {"tech_name": "Tailwind CSS", "percentage": 1},
            {"tech_name": "Bootstrap", "percentage": 1},
            {"tech_name": "Material UI", "percentage": 1},
            {"tech_name": "Chakra UI", "percentage": 1},
            {"tech_name": "Storybook", "percentage": 1},
            {"tech_name": "Figma", "percentage": 1},
            {"tech_name": "Zeplin", "percentage": 1},
            {"tech_name": "InVision", "percentage": 1}
        ],
        "experienced_tech_stacks": [
            {"tech_name": "JavaScript", "percentage": 45},
            {"tech_name": "React", "percentage": 30},
            {"tech_name": "TypeScript", "percentage": 25},
            {"tech_name": "HTML", "percentage": 15},
            {"tech_name": "Redux", "percentage": 10},
            {"tech_name": "SASS", "percentage": 8},
            {"tech_name": "Webpack", "percentage": 5},
            {"tech_name": "GraphQL", "percentage": 5},
            {"tech_name": "Apollo", "percentage": 4},
            {"tech_name": "Node.js", "percentage": 4},
            {"tech_name": "Express.js", "percentage": 3},
            {"tech_name": "Jest", "percentage": 3},
            {"tech_name": "Cypress", "percentage": 3},
            {"tech_name": "Webpack", "percentage": 3},
            {"tech_name": "Babel", "percentage": 3},
            {"tech_name": "D3.js", "percentage": 2},
            {"tech_name": "Three.js", "percentage": 2},
            {"tech_name": "Vue.js", "percentage": 2},
            {"tech_name": "Nuxt.js", "percentage": 2},
            {"tech_name": "Gatsby", "percentage": 2},
            {"tech_name": "Next.js", "percentage": 2},
            {"tech_name": "Svelte", "percentage": 2},
            {"tech_name": "Tailwind CSS", "percentage": 2},
            {"tech_name": "Bootstrap", "percentage": 2},
            {"tech_name": "Material UI", "percentage": 2},
            {"tech_name": "Chakra UI", "percentage": 2},
            {"tech_name": "Storybook", "percentage": 1},
            {"tech_name": "Figma", "percentage": 1},
            {"tech_name": "Zeplin", "percentage": 1},
            {"tech_name": "InVision", "percentage": 1}
        ]
    },
    {
        "job_title": "데이터 엔지니어",
        "entry_tech_stacks": [
            {"tech_name": "Python", "percentage": 35},
            {"tech_name": "SQL", "percentage": 25},
            {"tech_name": "Apache Spark", "percentage": 20},
            {"tech_name": "Hadoop", "percentage": 15},
            {"tech_name": "ETL", "percentage": 10},
            {"tech_name": "Docker", "percentage": 8},
            {"tech_name": "Kafka", "percentage": 6},
            {"tech_name": "Airflow", "percentage": 5},
            {"tech_name": "MongoDB", "percentage": 4},
            {"tech_name": "PostgreSQL", "percentage": 4},
            {"tech_name": "AWS", "percentage": 3},
            {"tech_name": "GCP", "percentage": 2},
            {"tech_name": "Azure", "percentage": 2},
            {"tech_name": "NoSQL", "percentage": 2},
            {"tech_name": "Git", "percentage": 1}
        ],
        "experienced_tech_stacks": [
            {"tech_name": "Python", "percentage": 40},
            {"tech_name": "SQL", "percentage": 30},
            {"tech_name": "Apache Spark", "percentage": 25},
            {"tech_name": "Hadoop", "percentage": 20},
            {"tech_name": "ETL", "percentage": 15},
            {"tech_name": "Docker", "percentage": 10},
            {"tech_name": "Kafka", "percentage": 8},
            {"tech_name": "Airflow", "percentage": 8},
            {"tech_name": "MongoDB", "percentage": 6},
            {"tech_name": "PostgreSQL", "percentage": 6},
            {"tech_name": "AWS", "percentage": 5},
            {"tech_name": "GCP", "percentage": 4},
            {"tech_name": "Azure", "percentage": 4},
            {"tech_name": "NoSQL", "percentage": 4},
            {"tech_name": "Git", "percentage": 3}
        ]
    },
    {
        "job_title": "데브옵스",
        "entry_tech_stacks": [
            {"tech_name": "AWS", "percentage": 30},
            {"tech_name": "Docker", "percentage": 25},
            {"tech_name": "Kubernetes", "percentage": 20},
            {"tech_name": "Linux", "percentage": 15},
            {"tech_name": "Terraform", "percentage": 10},
            {"tech_name": "Ansible", "percentage": 8},
            {"tech_name": "Git", "percentage": 5},
            {"tech_name": "CI/CD", "percentage": 5},
            {"tech_name": "Jenkins", "percentage": 4},
            {"tech_name": "Prometheus", "percentage": 4},
            {"tech_name": "Grafana", "percentage": 3},
            {"tech_name": "Apache", "percentage": 3},
            {"tech_name": "Nginx", "percentage": 3},
            {"tech_name": "Python", "percentage": 2},
            {"tech_name": "Bash", "percentage": 2},
            {"tech_name": "SQL", "percentage": 2},
            {"tech_name": "Monitoring", "percentage": 2}
        ],
        "experienced_tech_stacks": [
            {"tech_name": "AWS", "percentage": 40},
            {"tech_name": "Docker", "percentage": 35},
            {"tech_name": "Kubernetes", "percentage": 30},
            {"tech_name": "Linux", "percentage": 25},
            {"tech_name": "Terraform", "percentage": 20},
            {"tech_name": "Ansible", "percentage": 15},
            {"tech_name": "Git", "percentage": 10},
            {"tech_name": "CI/CD", "percentage": 10},
            {"tech_name": "Jenkins", "percentage": 8},
            {"tech_name": "Prometheus", "percentage": 7},
            {"tech_name": "Grafana", "percentage": 5},
            {"tech_name": "Apache", "percentage": 5},
            {"tech_name": "Nginx", "percentage": 5},
            {"tech_name": "Python", "percentage": 4},
            {"tech_name": "Bash", "percentage": 4},
            {"tech_name": "SQL", "percentage": 4},
            {"tech_name": "Monitoring", "percentage": 4}
        ]
    },
    {
        "job_title": "모바일 개발자",
        "entry_tech_stacks": [
            {"tech_name": "JavaScript", "percentage": 30},
            {"tech_name": "React", "percentage": 25},
            {"tech_name": "Node.js", "percentage": 20},
            {"tech_name": "HTML", "percentage": 10},
            {"tech_name": "CSS", "percentage": 8},
            {"tech_name": "PostgreSQL", "percentage": 5},
            {"tech_name": "Express.js", "percentage": 3},
            {"tech_name": "Git", "percentage": 3},
            {"tech_name": "Docker", "percentage": 3},
            {"tech_name": "GraphQL", "percentage": 2},
            {"tech_name": "REST API", "percentage": 2},
            {"tech_name": "Redux", "percentage": 2}
        ],
        "experienced_tech_stacks": [
            {"tech_name": "JavaScript", "percentage": 40},
            {"tech_name": "React", "percentage": 30},
            {"tech_name": "Node.js", "percentage": 25},
            {"tech_name": "HTML", "percentage": 15},
            {"tech_name": "CSS", "percentage": 10},
            {"tech_name": "PostgreSQL", "percentage": 8},
            {"tech_name": "Express.js", "percentage": 5},
            {"tech_name": "Git", "percentage": 5},
            {"tech_name": "Docker", "percentage": 4},
            {"tech_name": "GraphQL", "percentage": 4},
            {"tech_name": "REST API", "percentage": 4},
            {"tech_name": "Redux", "percentage": 4}
        ]
    }
]




# data = [
#     {
#         "job_title": "백엔드",
#         "entry_tech_stacks": [
#             {"tech_name": "Python", "percentage": 30},
#             {"tech_name": "SQL", "percentage": 25},
#             {"tech_name": "Django", "percentage": 20},
#             {"tech_name": "Flask", "percentage": 10},
#             {"tech_name": "PostgreSQL", "percentage": 8},
#             {"tech_name": "Docker", "percentage": 5},
#             {"tech_name": "Redis", "percentage": 2},
#             {"tech_name": "MongoDB", "percentage": 1},
#             {"tech_name": "GraphQL", "percentage": 1},
#             {"tech_name": "Kubernetes", "percentage": 1},
#             {"tech_name": "Celery", "percentage": 1},
#             {"tech_name": "Nginx", "percentage": 1},
#             {"tech_name": "Gunicorn", "percentage": 1},
#             {"tech_name": "Jenkins", "percentage": 1},
#             {"tech_name": "Ansible", "percentage": 1},
#             {"tech_name": "Terraform", "percentage": 1},
#             {"tech_name": "Linux", "percentage": 1},
#             {"tech_name": "AWS", "percentage": 1},
#             {"tech_name": "GCP", "percentage": 1},
#             {"tech_name": "Azure", "percentage": 1},
#             {"tech_name": "MySQL", "percentage": 1},
#             {"tech_name": "SQLite", "percentage": 1},
#             {"tech_name": "OracleDB", "percentage": 1},
#             {"tech_name": "Selenium", "percentage": 1},
#             {"tech_name": "Pandas", "percentage": 1},
#             {"tech_name": "NumPy", "percentage": 1},
#             {"tech_name": "Matplotlib", "percentage": 1},
#             {"tech_name": "Pytest", "percentage": 1},
#             {"tech_name": "Git", "percentage": 1}
#         ],
#         "experienced_tech_stacks": [
#             {"tech_name": "Python", "percentage": 40},
#             {"tech_name": "SQL", "percentage": 30},
#             {"tech_name": "Django", "percentage": 25},
#             {"tech_name": "Flask", "percentage": 15},
#             {"tech_name": "PostgreSQL", "percentage": 10},
#             {"tech_name": "Docker", "percentage": 8},
#             {"tech_name": "Redis", "percentage": 5},
#             {"tech_name": "MongoDB", "percentage": 4},
#             {"tech_name": "GraphQL", "percentage": 4},
#             {"tech_name": "Kubernetes", "percentage": 4},
#             {"tech_name": "Celery", "percentage": 4},
#             {"tech_name": "Nginx", "percentage": 3},
#             {"tech_name": "Gunicorn", "percentage": 3},
#             {"tech_name": "Jenkins", "percentage": 3},
#             {"tech_name": "Ansible", "percentage": 2},
#             {"tech_name": "Terraform", "percentage": 2},
#             {"tech_name": "Linux", "percentage": 2},
#             {"tech_name": "AWS", "percentage": 2},
#             {"tech_name": "GCP", "percentage": 2},
#             {"tech_name": "Azure", "percentage": 2},
#             {"tech_name": "MySQL", "percentage": 2},
#             {"tech_name": "SQLite", "percentage": 2},
#             {"tech_name": "OracleDB", "percentage": 2},
#             {"tech_name": "Selenium", "percentage": 1},
#             {"tech_name": "Pandas", "percentage": 1},
#             {"tech_name": "NumPy", "percentage": 1},
#             {"tech_name": "Matplotlib", "percentage": 1},
#             {"tech_name": "Pytest", "percentage": 1},
#             {"tech_name": "Git", "percentage": 1}
#         ]
#     },
#     {
#         "job_title": "프론트엔드",
#         "entry_tech_stacks": [
#             {"tech_name": "JavaScript", "percentage": 35},
#             {"tech_name": "React", "percentage": 25},
#             {"tech_name": "CSS", "percentage": 20},
#             {"tech_name": "HTML", "percentage": 10},
#             {"tech_name": "Redux", "percentage": 5},
#             {"tech_name": "TypeScript", "percentage": 4},
#             {"tech_name": "SASS", "percentage": 3},
#             {"tech_name": "Webpack", "percentage": 2},
#             {"tech_name": "GraphQL", "percentage": 2},
#             {"tech_name": "Apollo", "percentage": 2},
#             {"tech_name": "Node.js", "percentage": 1},
#             {"tech_name": "Express.js", "percentage": 1},
#             {"tech_name": "Jest", "percentage": 1},
#             {"tech_name": "Cypress", "percentage": 1},
#             {"tech_name": "Webpack", "percentage": 1},
#             {"tech_name": "Babel", "percentage": 1},
#             {"tech_name": "D3.js", "percentage": 1},
#             {"tech_name": "Three.js", "percentage": 1},
#             {"tech_name": "Vue.js", "percentage": 1},
#             {"tech_name": "Nuxt.js", "percentage": 1},
#             {"tech_name": "Gatsby", "percentage": 1},
#             {"tech_name": "Next.js", "percentage": 1},
#             {"tech_name": "Svelte", "percentage": 1},
#             {"tech_name": "Tailwind CSS", "percentage": 1},
#             {"tech_name": "Bootstrap", "percentage": 1},
#             {"tech_name": "Material UI", "percentage": 1},
#             {"tech_name": "Chakra UI", "percentage": 1},
#             {"tech_name": "Storybook", "percentage": 1},
#             {"tech_name": "Figma", "percentage": 1},
#             {"tech_name": "Zeplin", "percentage": 1},
#             {"tech_name": "InVision", "percentage": 1}
#         ],
#         "experienced_tech_stacks": [
#             {"tech_name": "JavaScript", "percentage": 45},
#             {"tech_name": "React", "percentage": 30},
#             {"tech_name": "TypeScript", "percentage": 25},
#             {"tech_name": "HTML", "percentage": 15},
#             {"tech_name": "Redux", "percentage": 10},
#             {"tech_name": "SASS", "percentage": 8},
#             {"tech_name": "Webpack", "percentage": 5},
#             {"tech_name": "GraphQL", "percentage": 5},
#             {"tech_name": "Apollo", "percentage": 4},
#             {"tech_name": "Node.js", "percentage": 4},
#             {"tech_name": "Express.js", "percentage": 3},
#             {"tech_name": "Jest", "percentage": 3},
#             {"tech_name": "Cypress", "percentage": 3},
#             {"tech_name": "Webpack", "percentage": 3},
#             {"tech_name": "Babel", "percentage": 3},
#             {"tech_name": "D3.js", "percentage": 2},
#             {"tech_name": "Three.js", "percentage": 2},
#             {"tech_name": "Vue.js", "percentage": 2},
#             {"tech_name": "Nuxt.js", "percentage": 2},
#             {"tech_name": "Gatsby", "percentage": 2},
#             {"tech_name": "Next.js", "percentage": 2},
#             {"tech_name": "Svelte", "percentage": 2},
#             {"tech_name": "Tailwind CSS", "percentage": 2},
#             {"tech_name": "Bootstrap", "percentage": 2},
#             {"tech_name": "Material UI", "percentage": 2},
#             {"tech_name": "Chakra UI", "percentage": 2},
#             {"tech_name": "Storybook", "percentage": 1},
#             {"tech_name": "Figma", "percentage": 1},
#             {"tech_name": "Zeplin", "percentage": 1},
#             {"tech_name": "InVision", "percentage": 1}
#         ]
#     }
# ]