# Generated by Django 5.1.2 on 2024-10-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobMarket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
