# Generated by Django 5.0.6 on 2024-10-17 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobMarket", "0003_chartfour"),
        ("jobMarket", "0003_job_skill"),
    ]

    operations = []
