# Generated by Django 5.1.2 on 2024-10-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobMarket', '0004_merge_0003_chartfour_0003_job_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingByJobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('collected_on', models.DateTimeField(verbose_name='데이터 수집 일자')),
                ('job_sub_type_name', models.CharField(max_length=100, verbose_name='하위 직군 이름')),
                ('count', models.IntegerField(verbose_name='공고 수')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='job_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='하위 직군 이름'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job_need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobMarket.jobneed', verbose_name='기술 요구 직군'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='percentage',
            field=models.FloatField(verbose_name='백분율'),
        ),
    ]
