# Generated by Django 5.1.2 on 2024-10-18 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobMarket', '0005_postingbyjobposition_alter_jobneed_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingByJobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=50, verbose_name='지역 이름')),
                ('experience_level', models.CharField(max_length=20, verbose_name='경력')),
                ('rate', models.FloatField(verbose_name='백분율')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='postingbyjobposition',
            name='collected_on',
            field=models.DateTimeField(verbose_name='데이터 수집 일시'),
        ),
        migrations.AlterField(
            model_name='postingbyjobposition',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='공고 수'),
        ),
    ]
